## Importing all the lib

In [414]:
import pandas  as pd

In [362]:
data = pd.read_csv("data/laptops_raw.csv")

In [363]:
data.head(5)

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...","₹1,18,498","₹1,11,102"
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...","₹1,15,898","₹1,10,902"
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹48,990","₹40,990"
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,"₹50,990","₹37,990"
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,"₹1,20,928","₹1,12,800"

In [364]:
data.shape

(960, 3)

In [365]:
data.isnull().sum()

brand              0
original_price    29
current_price      0
dtype: int64

In [366]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   brand           960 non-null    str
 1   original_price  931 non-null    str
 2   current_price   960 non-null    str
dtypes: str(3)
memory usage: 137.7 KB

In [367]:
data.head()

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...","₹1,18,498","₹1,11,102"
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...","₹1,15,898","₹1,10,902"
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹48,990","₹40,990"
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,"₹50,990","₹37,990"
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,"₹1,20,928","₹1,12,800"

In [368]:
# cleaning prices and converting them into float/int
def clean_price(prices):
    cleaned_list = []
    for price in prices:
        if pd.isnull(price):
            cleaned_list.append(None)
        else:
            cleaned_list.append(float(str(price).replace("₹","").replace(",","")))
    return cleaned_list 

data["current_price"] = clean_price(data["current_price"])
data["original_price"] = clean_price(data["original_price"])

In [369]:
data.head()

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...",118498.0,111102.0
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...",115898.0,110902.0
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,48990.0,40990.0
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,50990.0,37990.0
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,120928.0,112800.0

In [370]:
data.dtypes

brand                 str
original_price    float64
current_price     float64
dtype: object

In [371]:
print(data[["current_price", "original_price"]].describe())

       current_price  original_price
count     960.000000      931.000000
mean    96205.811458   120948.050483
std     69647.908448    77609.773749
min     14962.000000    16298.000000
25%     59990.000000    78492.000000
50%     80990.000000   104990.000000
75%    108990.000000   119945.000000
max    497436.000000   509990.000000

## Adding Discount Col

In [372]:
data["discount_price"] = abs((data["original_price"] - data["current_price"] ) / data["original_price"] * 100)

In [373]:
data.head()

,brand,original_price,current_price,discount_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...",118498.0,111102.0,6.241456
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...",115898.0,110902.0,4.310687
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,48990.0,40990.0,16.329863
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,50990.0,37990.0,25.495195
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,120928.0,112800.0,6.721355

In [374]:
data.describe()

       original_price  current_price  discount_price
count      931.000000     960.000000      931.000000
mean    120948.050483   96205.811458       61.635584
std      77609.773749   69647.908448       86.724645
min      16298.000000   14962.000000        0.000000
25%      78492.000000   59990.000000       22.467430
50%     104990.000000   80990.000000       44.444444
75%     119945.000000  108990.000000       66.900444
max     509990.000000  497436.000000     1066.672222

In [377]:
# find the bad rows
bad = data[data["discount_price"] > 80]
print(len(bad))
print(bad[["brand", "original_price", "current_price", "discount_price"]].head(10))

40
                                                 brand  original_price  \
10   MOTOROLA Motobook 60 Pro Full Metal OLED AI PC...        389990.0
34   ASUS Expertbook P3 Metal High-performance proc...        389990.0
38   Acer Aspire Intel Celeron Dual Core N4500 - (1...        119498.0
58   Acer Aspire 3 Intel Core i3 12th Gen 1215U - (...        389990.0
59   Lenovo 100e Chromebook Gen 4 MediaTek Kompanio...        176990.0
83   MSI Modern 14 Intel Core i3 13th Gen 1315U - (...        389990.0
94   Acer Chromebook Intel Celeron Dual Core N4500 ...        115898.0
103  HP 14 AI PC Intel Core Ultra 7 155H - (16 GB/5...        389990.0
127  MOTOROLA Motobook 60 Pro Full Metal OLED AI PC...        389990.0
152  HP 15 (i3 14th Gen) Intel Core 3 100U - (8 GB/...        389990.0

     current_price  discount_price
10         59990.0       84.617554
34         66093.0       83.052642
38         20990.0       82.434852
58         36990.0       90.515141
59         14990.0       91.530595
83         44990.0       88.463807
94         21990.0       81.026420
103        74768.0       80.828226
127        59990.0       84.617554
152        50190.0       87.130439

In [378]:
# keep only rows where current <= original (makes real sense)
data = data[data["current_price"] <= data["original_price"]]
print(data.shape)
print(data["discount_price"].describe())

(614, 4)
count    614.000000
mean      42.215845
std       23.881828
min        0.000000
25%       24.265768
50%       42.863674
75%       60.305016
max       95.384753
Name: discount_price, dtype: float64

In [379]:
data.describe()

       original_price  current_price  discount_price
count      614.000000     614.000000      614.000000
mean    143329.286645   70333.894137       42.215845
std      84330.673502   26335.237050       23.881828
min      27990.000000   14962.000000        0.000000
25%      99817.500000   52157.750000       24.265768
50%     115898.000000   61949.500000       42.863674
75%     170990.000000   88990.000000       60.305016
max     509990.000000  209900.000000       95.384753

In [380]:
data["brand"]

0      MICROSOFT Surface Pro 12" with Type Cover & Pe...
1      MICROSOFT Surface Pro 12" with Pen Core 8 Snap...
2      ASUS Vivobook Go 15 (2025) with Office 2024 + ...
3      ASUS Vivobook 15 (2025) with Office 2024 + M36...
4      HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...
                             ...
925    ASUS Zenbook 14X OLED Space Edition Touchscree...
927    ASUS ExpertBook P3 Intel Core Ultra 5 225H - (...
928    Lenovo IdeaPad Slim 5 Intel Core i7 13th Gen 1...
929    Lenovo IdeaPad 1 MSO'2024 AMD Ryzen 5 Hexa Cor...
930    MICROSOFT Surface Pro 12" with Type Cover Core...
Name: brand, Length: 614, dtype: str

## Extracting Ram and other specification

In [381]:
import re # regex

In [382]:
def extract_ram(text):
    match = re.search(r'(\d+)\s*GB', str(text))
    return int(match.group(1)) if match else None

# apply row by row
data["ram"] = data["brand"].apply(extract_ram)
print(data["ram"].value_counts())

ram
16.0    416
8.0     146
4.0      14
24.0      8
32.0      8
12.0      3
Name: count, dtype: int64

In [383]:
data["ram"] = data["brand"].apply(extract_ram)

In [384]:
df = data

## More columns to extract

col : brand , processor , storage, graphics, os, product name

In [385]:
def extract_storage(text):
    # handle TB first
    match_tb = re.search(r'(\d+)\s*TB', str(text))
    if match_tb:
        return int(match_tb.group(1)) * 1024  # convert to GB
    
    # then GB SSD
    match_gb = re.search(r'(\d+)\s*GB\s*SSD', str(text))
    if match_gb:
        return int(match_gb.group(1))
    
    return None

data["storage"] = data["brand"].apply(extract_storage)
print(data["storage"].value_counts())

storage
512.0     431
1024.0     76
256.0      50
128.0       2
2048.0      1
Name: count, dtype: int64

In [386]:
df.isnull().sum()

brand              0
original_price     0
current_price      0
discount_price     0
ram               19
storage           54
dtype: int64

In [387]:
def extract_os(text):
    match = re.search(r'(Windows \d+|DOS|Ubuntu)', str(text))
    return match.group(1) if match else None

data["os"] = data["brand"].apply(extract_os)

In [388]:
def extract_graphics(text):
    match = re.search(r'(\d+\s*GB\s*Graphics|NVIDIA|AMD Radeon|Intel Iris)', str(text))
    return match.group(1) if match else "Integrated"

In [389]:
def extract_processor(text):
    match = re.search(r'(Intel Core [^\s]+|AMD Ryzen \d+|Snapdragon [^\s]+|Apple M\d)', str(text))
    return match.group(1) if match else None

In [390]:
def extract_brand(text):
    return str(text).split()[0]

In [391]:
data["graphics"]     = data["brand"].apply(extract_graphics)
data["processor"]    = data["brand"].apply(extract_processor)
data["brand"]   = data["brand"].apply(extract_brand)

In [392]:
df["os"] = df["os"].replace("Windows 1", "Windows 11")

In [393]:
df["os"].value_counts()

os
Windows 11    519
Windows 10     14
Ubuntu          1
Name: count, dtype: int64

In [394]:
df["storage"].value_counts()

storage
512.0     431
1024.0     76
256.0      50
128.0       2
2048.0      1
Name: count, dtype: int64

In [395]:
df["brand"].value_counts()

brand
ASUS          128
HP            121
MOTOROLA       70
Lenovo         68
MICROSOFT      63
Acer           63
DELL           38
MSI            23
Ultimus         9
Samsung         9
Infinix         6
Apple           6
Colorful        2
Thomson         2
WINGS           2
ZEBRONICS       1
Avita           1
WarnerCann      1
Primebook       1
Name: count, dtype: int64

In [396]:
df["processor"].value_counts()

processor
Intel Core Ultra        166
Intel Core i5           112
Snapdragon X             67
AMD Ryzen 5              53
Intel Core i3            52
Intel Core i7            36
AMD Ryzen 7              21
AMD Ryzen 3              20
Intel Core 5             18
Intel Core 3             14
Intel Core 7              8
AMD Ryzen 9               1
Intel Core i9             1
Intel Core i5-13420H      1
Name: count, dtype: int64

In [397]:
df["graphics"].value_counts()

graphics
Integrated       556
6 GB Graphics     25
4 GB Graphics     21
8 GB Graphics      7
2 GB Graphics      3
1 GB Graphics      1
AMD Radeon         1
Name: count, dtype: int64

In [398]:
df

,brand,original_price,current_price,discount_price,ram,storage,os,graphics,processor
0,MICROSOFT,118498.0,111102.0,6.241456,16.0,256.0,Windows 11,Integrated,Snapdragon X
1,MICROSOFT,115898.0,110902.0,4.310687,16.0,512.0,Windows 11,Integrated,Snapdragon X
2,ASUS,48990.0,40990.0,16.329863,8.0,NaN,NaN,Integrated,AMD Ryzen 5
3,ASUS,50990.0,37990.0,25.495195,8.0,512.0,NaN,Integrated,Intel Core i3
4,HP,120928.0,112800.0,6.721355,24.0,1024.0,Windows 11,8 GB Graphics,AMD Ryzen 7
...,...,...,...,...,...,...,...,...,...
925,ASUS,347990.0,98991.0,71.553493,16.0,NaN,NaN,Integrated,Intel Core i5
927,ASUS,109999.0,88990.0,19.099265,16.0,512.0,Windows 11,Integrated,Intel Core Ultra
928,Lenovo,192990.0,84990.0,55.961449,16.0,512.0,Windows 11,Integrated,Intel Core i7
929,Lenovo,79990.0,49990.0,37.504688,16.0,512.0,NaN,Integrated,AMD Ryzen 5
930,MICROSOFT,113216.0,103822.0,8.297414,16.0,256.0,Windows 11,Integrated,Snapdragon X

In [399]:
df.isnull().sum()

brand              0
original_price     0
current_price      0
discount_price     0
ram               19
storage           54
os                80
graphics           0
processor         44
dtype: int64

In [403]:
df.info()

<class 'pandas.DataFrame'>
Index: 614 entries, 0 to 930
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   brand           614 non-null    str
 1   original_price  614 non-null    float64
 2   current_price   614 non-null    float64
 3   discount_price  614 non-null    float64
 4   ram             595 non-null    float64
 5   storage         560 non-null    float64
 6   os              534 non-null    str
 7   graphics        614 non-null    str
 8   processor       570 non-null    str
dtypes: float64(5), str(4)
memory usage: 69.9 KB

In [404]:
def fill_value(df):
    for col in df.columns :
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(df[col].median())
        else :
            df[col] = df[col].fillna(df[col].mode()[0])
        
    return df

In [406]:
df = fill_value(df)

In [407]:
df.isnull().sum()

brand             0
original_price    0
current_price     0
discount_price    0
ram               0
storage           0
os                0
graphics          0
processor         0
dtype: int64

In [410]:
df.reset_index(drop=True, inplace=True)

In [411]:
print(data.isnull().sum())
print(data.shape)

brand             0
original_price    0
current_price     0
discount_price    0
ram               0
storage           0
os                0
graphics          0
processor         0
dtype: int64
(614, 9)

In [417]:
df.to_csv("data/processed/laptops_cleaned.csv")
print("Saved!!")

Saved!!