## Importing all the lib

In [3]:
import pandas  as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
data = pd.read_csv("data/laptops_raw.csv")

In [19]:
data.head(5)

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...","₹1,18,498","₹1,11,102"
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...","₹1,15,898","₹1,10,902"
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹48,990","₹40,990"
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,"₹50,990","₹37,990"
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,"₹1,20,928","₹1,12,800"

In [20]:
data.shape

(960, 3)

In [21]:
data.isnull().sum()

brand              0
original_price    29
current_price      0
dtype: int64

In [22]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   brand           960 non-null    str
 1   original_price  931 non-null    str
 2   current_price   960 non-null    str
dtypes: str(3)
memory usage: 137.7 KB

In [23]:
data.head()

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...","₹1,18,498","₹1,11,102"
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...","₹1,15,898","₹1,10,902"
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹48,990","₹40,990"
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,"₹50,990","₹37,990"
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,"₹1,20,928","₹1,12,800"

In [31]:
# cleaning prices and converting them into float/int
def clean_price(prices):
    cleaned_list = []
    for price in prices:
        if pd.isnull(price):
            cleaned_list.append(None)
        else:
            cleaned_list.append(float(str(price).replace("₹","").replace(",","")))
    return cleaned_list 

data["current_price"] = clean_price(data["current_price"])
data["original_price"] = clean_price(data["original_price"])

In [ ]:
data.head()

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...",118498.0,111102.0
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...",115898.0,111102.0
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,48990.0,111102.0
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,50990.0,111102.0
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,120928.0,111102.0

In [36]:
data.dtypes

brand                 str
original_price    float64
current_price     float64
dtype: object

In [38]:
print(data[["current_price", "original_price"]].describe())

       current_price  original_price
count          960.0      931.000000
mean        111102.0   120948.050483
std              0.0    77609.773749
min         111102.0    16298.000000
25%         111102.0    78492.000000
50%         111102.0   104990.000000
75%         111102.0   119945.000000
max         111102.0   509990.000000