## Importing all the lib

In [63]:
import pandas  as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [64]:
data = pd.read_csv("data/laptops_raw.csv")

In [65]:
data.head(5)

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...","₹1,18,498","₹1,11,102"
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...","₹1,15,898","₹1,10,902"
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹48,990","₹40,990"
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,"₹50,990","₹37,990"
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,"₹1,20,928","₹1,12,800"

In [66]:
data.shape

(960, 3)

In [67]:
data.isnull().sum()

brand              0
original_price    29
current_price      0
dtype: int64

In [68]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   brand           960 non-null    str
 1   original_price  931 non-null    str
 2   current_price   960 non-null    str
dtypes: str(3)
memory usage: 137.7 KB

In [69]:
data.head()

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...","₹1,18,498","₹1,11,102"
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...","₹1,15,898","₹1,10,902"
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,"₹48,990","₹40,990"
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,"₹50,990","₹37,990"
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,"₹1,20,928","₹1,12,800"

In [70]:
# cleaning prices and converting them into float/int
def clean_price(prices):
    cleaned_list = []
    for price in prices:
        if pd.isnull(price):
            cleaned_list.append(None)
        else:
            cleaned_list.append(float(str(price).replace("₹","").replace(",","")))
    return cleaned_list 

data["current_price"] = clean_price(data["current_price"])
data["original_price"] = clean_price(data["original_price"])

In [71]:
data.head()

,brand,original_price,current_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...",118498.0,111102.0
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...",115898.0,110902.0
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,48990.0,40990.0
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,50990.0,37990.0
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,120928.0,112800.0

In [72]:
data.dtypes

brand                 str
original_price    float64
current_price     float64
dtype: object

In [73]:
print(data[["current_price", "original_price"]].describe())

       current_price  original_price
count     960.000000      931.000000
mean    96205.811458   120948.050483
std     69647.908448    77609.773749
min     14962.000000    16298.000000
25%     59990.000000    78492.000000
50%     80990.000000   104990.000000
75%    108990.000000   119945.000000
max    497436.000000   509990.000000

## Adding Discount Col

In [74]:
data["discount_price"] = abs((data["original_price"] - data["current_price"] ) / data["original_price"] * 100)

In [75]:
data.head()

,brand,original_price,current_price,discount_price
0,"MICROSOFT Surface Pro 12"" with Type Cover & Pe...",118498.0,111102.0,6.241456
1,"MICROSOFT Surface Pro 12"" with Pen Core 8 Snap...",115898.0,110902.0,4.310687
2,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,48990.0,40990.0,16.329863
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,50990.0,37990.0,25.495195
4,HP Victus AI AMD Ryzen 7 Octa Core 260 - (24 G...,120928.0,112800.0,6.721355

In [76]:
data.describe()

       original_price  current_price  discount_price
count      931.000000     960.000000      931.000000
mean    120948.050483   96205.811458       61.635584
std      77609.773749   69647.908448       86.724645
min      16298.000000   14962.000000        0.000000
25%      78492.000000   59990.000000       22.467430
50%     104990.000000   80990.000000       44.444444
75%     119945.000000  108990.000000       66.900444
max     509990.000000  497436.000000     1066.672222

In [77]:
# find the bad rows
bad = data[data["discount_price"] > 80]
print(len(bad))
print(bad[["brand", "original_price", "current_price", "discount_price"]].head(10))

147
                                                brand  original_price  \
10  MOTOROLA Motobook 60 Pro Full Metal OLED AI PC...        389990.0
11  ASUS ExpertBook Ultra Copilot+ PC Intel Core U...         77507.0
23  Lenovo IdeaPad Slim 3 AMD Ryzen 7 Octa Core 88...         35990.0
30  MOTOROLA Motobook 60 Pro Full Metal OLED AI PC...         27990.0
34  ASUS Expertbook P3 Metal High-performance proc...        389990.0
36  ASUS ExpertBook Ultra Copilot+ PC Intel Core U...         29999.0
38  Acer Aspire Intel Celeron Dual Core N4500 - (1...        119498.0
47  ASUS ExpertBook P3 Intel Core Ultra 7 255H - (...         44990.0
51  MICROSOFT Surface Pro 12" with Pen Core 8 Snap...         54990.0
57  MOTOROLA Motobook 60 Pro Full Metal OLED AI PC...         16298.0

    current_price  discount_price
10        59990.0       84.617554
11       349990.0      351.559214
23        83990.0      133.370381
30        59990.0      114.326545
34        66093.0       83.052642
36       349990.0     1066.672222
38        20990.0       82.434852
47       103990.0      131.140253
51       110902.0      101.676668
57        59990.0      268.081973

In [78]:
# keep only rows where current <= original (makes real sense)
data = data[data["current_price"] <= data["original_price"]]
print(data.shape)
print(data["discount_price"].describe())

(614, 4)
count    614.000000
mean      42.215845
std       23.881828
min        0.000000
25%       24.265768
50%       42.863674
75%       60.305016
max       95.384753
Name: discount_price, dtype: float64

In [79]:
data.describe()

       original_price  current_price  discount_price
count      614.000000     614.000000      614.000000
mean    143329.286645   70333.894137       42.215845
std      84330.673502   26335.237050       23.881828
min      27990.000000   14962.000000        0.000000
25%      99817.500000   52157.750000       24.265768
50%     115898.000000   61949.500000       42.863674
75%     170990.000000   88990.000000       60.305016
max     509990.000000  209900.000000       95.384753